training:
  lr: 0.005
  weight-decay: 0.0000001
  bs: 16
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 30 # Equidistant frames
  save-frequency: 10
  patience: 10
  
model:
  image-size: 224
  patch-size: 7
  num-classes: 1
  dim: 1024
  depth: 6
  dim-head: 64
  heads: 8
  mlp-dim: 2048
  emb-dim: 32
  dropout: 0.25
  emb-dropout: 0.25